packages:
  - "packages/*"
  - "apps/*"

catalogs:
  web:
    react: "^19.0.0"
    react-dom: "^19.0.0"
    next: "15.3.2"
    typescript: "^5"
    "@types/node": "^20"
    "@types/react": "^19"
    "@types/react-dom": "^19"
    "@tailwindcss/postcss": "^4"
    tailwindcss: "^4"
    eslint: "^9"
    "eslint-config-next": "15.3.2"
    "@eslint/eslintrc": "^3"
  server:
    dotenv: ^16.5.0
    fastify: ^5.3.3
    "fastify-plugin": ^5.0.1
    "@fastify/postgres": ^6.0.2
    nodemon: ^3.1.10
    "p-retry": ^6.2.1
    pg: ^8.16.0
    typescript: ^5.7.2
    ts-node: ^10.9.2
    "@types/node": ^22
    "@fastify/type-provider-typebox": ^5.1.0
    "@sinclair/typebox": ^0.34.33
